.PHONY = all statclib clean co

CFLAGS = -fPIC -I. -I.. -g -Wall -pedantic --pedantic-errors -I.

OBJS =   sigsegv.o

LIBOUT=libcrash.a

all:	staticlib  test1 test2

test1: staticlib
	$(CC) test1.c -I.. -L. -lpthread -lcrash -o test1
test2: staticlib
	$(CC) test2.c -I.. -L. -lpthread -lcrash -o test2

staticlib: $(OBJS)
	$(AR) cr $(LIBOUT) $(OBJS)

clean:
	- $(RM) -f $(OBJS) $(LIBOUT)  test1 test2

co:
	$(CO) RCS/*

